### ISSUE TITLE
FIR Filter Modification - Configurable Parameters with Default Value

### ISSUE THREAD

**Issue by obruendl** [paulscherrerinstitute/psi_fix#4]
Currently for all FIR filters in psi_fix, the user has to decide to use one of the options below:

1. Configurable coefficients (UseFixCoefs_g = 0). In this case, a DPRAM is implemented for coefficients and the default value after boot is all zeros. So the user must configure parameters (there are no default parameters)
2. Fixed coefficients (UseFixCoefs_g = 0). In this case, the user can pass compile-time define coefficients through FixCoefs_g that are implemented in a ROM. No configuration is required nor possible. So at runtime the parameters cannot be changed.

I would like to change this concept the following way:

1. Implement a DPRAM that allows setting the default values.
2. Use this DPRAM for coefficients in all FIR filters
3. Remove UseFIxCoefs_g and FixCoefs_g and replace them with one single parameter DefaultCoefs_g. After boot, DefaultCoefs_g (configurable at compile-time) are used but they can still be overwritten at run-time (because they are no implemented in the new DPRAM and not as ROM).

Looking at the functionality, this approach only has benefits and no drawbacks. I am writing an issue because the change is not 100% backwards compatible (parameter changes, so existing code using the FIR filters must be modified when psi_lib is upgraded, even though the change is very simple). So in my opinion, releasing this change would lead to an increment in the major version.

Do you agree with the change? Should I do it directly on develop or on a separate branch?

**Comment by rybaniec-r** [comment]
Having a DPRAM with default coefficients is a great idea and we should for sure go for it.  However, what I am thinking about is that it would be nice to preserve backward compatibility. This is important, because as you wrote, the change is a simple one.

Here are my ideas:

1.  We could use UseFixCoefs_g to enable/disable DPRAM and use FixCoefs_g to set the default values of the DPRAM. Advantage is that there would be no changes in the generics. However, FixCoefs_g is not an intuitive name for a default coefficient set.
2. We could introduce generic DefaultCoefs_g, which would only be used when UseFixCoefs_g is false. Now we would have a descriptive name for the DPRAM defaults. The drawback is, that we complicate the interface.

Maybe you will find another solution, which is backward compatible.

I like to do the development in a feature branch and merge it back to develop.

**Comment by obruendl** [comment]
I fully understand your concerns. The same points came to my mind when I started thinking about this.

I personally would prefer having a clean interface (even if it breaks backward compatibility):
1. If we let interfaces get more and more complicated with future changes because we do not want to break compatibility, interfaces will become messy and unusable at some point.
2. For new projects, I think clean and understandable interfaces are important.
3. For existing projects, the changes do not have any impact until the psi_fix submodule is upgraded (i.e. builds are still succeeding without any action required if the submodule is not changed).
4. Even if psi_fix is changed, the changes required are simple and should not lead to a major problem.

Could we meet half way?
- We leave the generic FixCoefs_g in (and we still generate a ROM and not a RAM if it is set)
- We rename FixCoefs_g to DefaultCoefs_g. This breaks compatibility but as it is only one paramter name that changes, it will be obvious to every developer what hed needs to modify in his code to compile again.

Would this work out for you?

As soon as we agree, I will do the changes on a feature branch.

**Comment by rybaniec-r** [comment]
Ok, I agree to break the interface. But how about using Coefs_g instead of DefaultCoefs_g?

**Comment by obruendl** [comment]
Fine for me. I will do so.

**Comment by obruendl** [comment]
Implemented
